# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Resolve Swift Packages
      run: xcodebuild -resolvePackageDependencies -project TV_SVT_Radio.xcodeproj
    - name: Build
      run: xcodebuild -scheme "TV_SVT_Radio" build CODE_SIGNING_ALLOWED=NO
     
